wordsListAr = {
'دستور': 'Constitution',
'تعديل دستوري': 'Constitutional Amendment',
'محكمة دستورية': 'Constitutional Court',
'قانون دستوري': 'Constitutional Law',
'نظام الحكم الملكي الدستوري': 'Constitutional Monarchy',
'احتواء': 'Containment',
'قضايا مثيرة للخلاف والنزاع': 'Contentious Issues',
'مساس بالعقد أو نقضه': 'Contract Tampering',
'مدان / محكوم عليه': 'Convicted',
'انقلاب / ثورة': 'Coup',
'محكمة الاستئناف': 'Court of Appeal',
'محكمة التمييز': 'Court of Cassation',
'المحكمة الابتدائية': 'Court of First Instance',
'زيارة مجاملة': 'Courtesy visit',
'شد عضلي': 'Cramps',
'ادارة الازمات': 'Crisis Management',
'سباق اختراق الضاحية': 'Cross-Country Race',
'استجواب بدقة': 'Cross-examination',
'بطولة الكأس': 'Cup Championship',
'الحد من': 'Curb',
 'صلاة الفجر': 'Dawn prayer',
'بحكم الأمر الواقع': 'De Facto',
'بحكم القانون': 'De Jure',
'المرحوم': 'Deceased',
'إعلان نتائج الاستطلاع': 'Declaration of Poll',
'اعلان المبادئ': 'Declaration of Principles',
'لبس الاحرام': 'Dedication grab',
'قذف / تشهير': 'Defamation',
'حكم غيابي': 'Default Judgment',
'شاهد نفي': 'Defense Witness',
'استخفاف/ تحد/ تمرد': 'Defiance',
'إضاعة الوقت بطريقة متعمدة': 'Deliberate Time Wasting',
'تداولي؛ تشاوري؛ متداول': 'Deliberative Capacity',
'منطقة مجردة من السلاح': 'Demilitarized zone',
'الاعتراض القانوني': 'Demurral ',
'نائب , نواب': 'Deputy (Deputies)',
'نائِبُ رَئِيسِ مَجْلِسِ النّوّاب': 'Deputy Speaker',
'سليل / حفيد': 'Descendant',
'طاغيه؛ ظالم؛ مستبد': 'Despot',
'استبداد أو طغيان؛ الحكم المستبد؛ حكم مطلق , جور': 'Despotism',
'زعزعة': 'Destabilization',
'الذمي / اهل الذمة': 'Dhimmi',
'غسيل كلوي': 'Dialysis',
'اقتراح مُعوِق': 'Dilatory Motion',
'المديرية العامة': 'Directorate General',
'متضارب': 'Discrepant',
'رمى القرص': 'Discus Throw',
'فك الارتباط': 'Disengagement',
'اشمئزاز؛ غثيان؛ يثير الاشمئزاز': 'Disgust',
'يفكك (عقار – مستوطنة)': 'Dismantle ',
'فك الرهن العقاري': 'Dis-mortgage',
'إحلال شيء محل شيء آخر؛ تشريد , نزوح': 'Displacement',
'معترض على قرار الحكم': 'Dissent',
'إبطال إجراءات قانونية؛ إلغاء وضع': 'Dissolution',
'طلاق بالوكالة': 'Divorce by proxy',
'افشى سرا / باح بالسر': 'Divulge ',
'العنف المنزلي / الُاسَري': 'Domestic violence',
'مسودة قانون': 'Draft Law',
'وضع مسودة': 'Drafting',
'تعادل': 'Draw',
'ضمادة ': 'Dressings (surgical)',
'رذاذ': 'Drizzle',
'إسقاط (/ انسحاب / رفع اليد)': 'Drop / (Withdraw)',
'جفاف': 'Drought',
'غائم': 'Dull (weather)',
'سلاله': 'Dynasty',
'تخصيص': 'Earmark (Earmarking)',
'المحكمة الكنسية': 'Ecclesiastic Court',
'تاريخ السريان': 'Effective Date',
'سنوات منقضية': 'Elapsed years',
'تزوير الانتخابات / احتيال أو خداع': 'Election rigging, fraud',
'فترة الحملة الانتخابية': 'Electoral Campaign Period',
'الحصة الانتخابية': 'Electoral Quota',
'اعدم بالكهرباء / صعق بالتيار الكهربائي': 'Electrocute',
'اختلاس': 'Embezzlement',
'اعتناق': 'Embracement',
'خالي الوفاض': 'Empty-handed',
'يُشَرع / يضع قانون': 'Enact',
'إلزامي / واجب النفاذ': 'Enforceable',
'مُعَمَق': 'Engrossing',
'مبعوث': 'Envoy',
'الصرع': 'Epilepsy',
'نزيف الأنف': 'Epistaxis',
'صلاة العشاء': 'Evening prayer',
'بِحُكم المنصب': 'Ex Officio',
'تفاقم': 'Exacerbation, worsening',
'تفاقم': 'Exacerbation, worsening',
'ما عدا ما ينص عليه القانون': 'Except as Provided by Law',
'تجاوز الولاية القضائية': 'Excess of Jurisdiction',
'إفطار المريض في رمضان': 'Exempting the sick person from Fasting in Ramadan',
'صوم كفارة': 'Expiatory fast',
'مذكرة تفسيرية / ايضاحية': 'Explanatory Memorandum',
'استغلال / تسخير': 'Exploitation',
'وقت إضافي': 'Extra Time / Added Time',
'متطرف': 'Extremist',
'تخلف عن': 'Fall behind',
'دفتر عائلة': 'Family register',
'متعصب': 'Fanatic',
'الصوم': 'Fasting ',
'المحاباة / المحسوبية': 'Favoritism',
'حكومة اتحادية': 'Federal government',
'جناية': 'Felony',
'تقديم دعوى مدنية': 'File for civil action',
'اتفاق نهائي عادل': 'Final Equitable Agreement',
'دوري كرة القدم': 'Football League',
'في اغلب الأحيان': 'For the most part',
'حق الامتياز': 'Franchise right',
'خداع / احتيال': 'Fraud',
'مصارعة حرة': 'Freestyle Wrestling',
'مباراة ودية': 'Friendly Match',
 'مكسو بالصقيع': 'Frosty',
'أحبط هذه المحاولة': 'Frustrate This Attempt',
'أصولي': 'Fundamentalist',
'ريح هوجاء': 'Gale',
'التهاب المرارة': 'Gall bladder inflammation ',
'مشنقة / مشانق': 'Gallows',
'أمر بالحجر على ممتلكات أو نقود': 'Garnishment order',
'فسح المجال لِ': 'Give place to ',
'الاحتباس الحراري': 'Global warming',
'حلق المرمى': 'Goalmouth',
'حكومة مستبدة': 'Government Autocracy',
'استبداد الحكومة': 'Government Despotism',
'جمباز': 'Gymnastics',
'بَرَد': 'Hail / hailstones',
'رمى كرة معدنية (مطرقة(': 'Hammer Throw',
'انتاجية متعثرة': 'Hampering productivity',
'أشْغالٌ شاقّة ': 'Hard Labor',
'هاترك (تسجيل 3 أهداف)': 'Hat-trick',
	'بواسير': 'Hemorrhoids',
'التهاب كبدي': 'Hepatitis',
'المشار اليها لاحقا': 'Hereinafter referred to ',
'خيانة عظمى': 'High treason',
'فروسية ( ركوب الخيل (': 'Horsemanship',
'الاتجار بالبشر': 'Human trafficking',
'الرطوبة': 'Humidity',
'سباق الحواجز': 'Hurdle Race',
'عقبة كأداء / مأزق ': 'Impasse',
'لا يتأثر / منيع': 'Impervious',
'بهاق': 'Impetigo',
'اكراما لِ': 'In deference to ',
'بين ظهرانينا': 'In our midst ',
'اعترافا؛ تَقْدِيراً لِـ': 'In Recognition Of',
'فيما يتعلق بِ': 'In respect of ',
'لا يشق له غبار': 'Incomparable',
'توغل': 'Incursion',
'العصمة': 'Infallibility',
'وريث / وارث': 'Inheritor',
'اصابة': 'Injury',
'عصيان': 'Insurrection',
'مخابرات': 'Intelligence',
'شفاعة': 'Intercession',
'المسرح الدولي': 'International arena',
'صندوق النقد الدولي': 'International Monetary Fund (IMF)',
'الاستجواب': 'Interrogation',
'امعاء': 'Intestines',
'الامعاء': 'Intestines',
'طلاق بائن بينونة كبرى': 'Irrevocable divorce',
'التعليمات الصادرة': 'Issued Instructions',
'رمى الرمح': 'Javelin Throw',
'هرولة': 'Jogging',
'بيان مشترك': 'Joint communiqué',
'استقلال القضاء': 'Judiciary Independence',
'الولاية القانونية': 'Jurisdiction',
'ضربة البداية': 'Kickoff',
'الألغام الأرضية': 'Land mine',
'المأسوف على (شبابه)': 'Late lamented, mourned',
'بطولة الدوري': 'League Championship',
'عقد ايجار': 'Leasing contract',
'درجة الخطورة': 'Level of severity',
'الملازم': 'Lieutenant',
'سجن مدى الحياة': 'Life imprisonment',
'مساعد الحكم (حامل الراية (': 'Linesman',
'الذخيرة الحية / رصاص حي': 'live ammunition',
'خط مكهرب': 'Live line',
'تمريرة طويلة': 'Long Pass',
'جَبُنَ': 'Lose heart                                   ',
'فقد اعتباره': 'Lose one\'s ground',
'فقد اعتباره': 'Lose one\'s ground',
'دفعة مالية كاملة المبلغ': 'Lump-sum payment',
'ورم خبيث': 'Malignant',
'انتداب (الانتداب البريطاني)': 'Mandate',
'الأحكام العرفية': 'Martial law',
'فضل رمضان': 'Merits of the month of Ramadan',
'لاعب وسط الملعب': 'Midfielder',
'تعبئه (عسكرية)': 'Mobilization',
'نجا بشق الانفس': 'Narrow escape',
'السُّرَّة': 'Navel',
'المحافظون الجدد': 'Neo-conservatives',
'المحسوبية': 'Nepotism',
'صلاة الظهر ': 'Noon prayer',
'الكاتب العدل': 'Notary Public',
'مبطلات الصوم': 'Nullification of fasting',
'الجريدة الرسمية': 'Official gazette',
'على أعتاب': 'On the threshold of',
'التهاب الاذن': 'Otitis',
'معتم': 'Overcast',
'نظرا لِ': 'Owing to ',
'خفقان القلب': 'Palpitation',
'منطقة الجزاء': 'Penalty Area',
'ضربة (ركلة) جزاء': 'Penalty Kick'}

wordsListEn = {value : key for (key, value) in wordsListAr.items()}